### PR TITLE
Add FreeDesktop support files

### PR DESCRIPTION
**Pull request by fpiesche**
These are:

- a `.desktop` file, which Linux desktop environments use to display applications in their app launcher menus
- an icon for the same
- a `.metainfo.xml` file, which can be used by packaging systems (either eg. deb/rpm/whatever system packages or, the use case for this entire PR, a Flatpak build I'm currently putting together) to display metadata about an application.

I've opted for the `itch.io` domain for the file names/app ID because for the purposes of the FreeDesktop standard, the app ID must be in `ext.domain.subdomain.app` format and `subdomain.domain.ext` must be an actually-existing site so the moddb URL would not have worked here.

### CODE REVIEW

**Comment by fpiesche** [comment]
Eep, hold on, just realised I forgot to fill in the OARS rating stuff properly. Will resubmit once that's sorted...

**Comment by fpiesche** [comment]
`.c``

**Comment by dibollinger** [comment]
Like I mentioned in the comments, use the itch.io link whereever possible. ModDB has extremely slow download speeds.

**Comment by fpiesche** [comment]
Updated a couple of the links to use the itch page instead :)

**Pull request merged**
